config/routes.rb
Rails.application.routes.draw do
  resources :heros do
    resources :file_uploads, only: [:new, :create, :destroy]
  end
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord
  validates :name, presence: true
  has_many_attached :files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  def new
    @hero = Hero.find(params[:hero_id])
  end

  def create
    hero = Hero.find(params[:hero_id])
    hero.files.attach(params[:hero][:files])
    redirect_to hero_path(hero)
  end

  def destroy
    @hero = Hero.find(params[:hero_id])
    @hero.files.find(params[:id]).purge
    redirect_to hero_path(@hero)
  end
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hero_params
      params.require(:hero).permit(:name, :bio, :birthday, :movies)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @search = params[:search]
    @heroes =
      if @search
        Hero
          .where('name like ?', "%#{@search}%")
      else
        Hero.all
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/file_uploads/new.html.erb
<h1>New avatar for Hero <%= @hero.name %></h1>
 
<%= form_with model: @hero, url: hero_file_uploads_path(@hero), method: :post, local: true do |f| %>
  <%= f.file_field :files, multiple: true %><br /><br />
  <%= f.submit 'Upload', class: 'btn btn-success btn-sm' %>
<% end %>

app/views/heros/_form.html.erb
<%= form_with(model: hero, local: true) do |form| %>
  <% if hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
        <% hero.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, class: "col-12 col-sm-3 col-md-3 col-lg-2 col-xl-2 col-form-label"  %>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
      <%= form.text_field :name, class: "form-control form-control-sm" %>
    </div>  
  </div>

  <div class="form-group row">
    <%= form.label :bio, class: "col-12 col-sm-3 col-md-3 col-lg-2 col-xl-2 col-form-label"  %>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
      <%= form.text_field :bio, class: "form-control form-control-sm" %>
    </div>  
  </div>

  <div class="form-group row">
    <%= form.label :birthday, class: "col-12 col-sm-3 col-md-3 col-lg-2 col-xl-2 col-form-label"  %>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
      <%= form.date_field :birthday, class: "form-control form-control-sm" %>
    </div>  
  </div>  

  <div class="form-group row">
    <%= form.label :movies, class: "col-12 col-sm-3 col-md-3 col-lg-2 col-xl-2 col-form-label"  %>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
      <%= form.text_field :movies, class: "form-control form-control-sm" %>
    </div>  
  </div>  

  <div class="actions">
    <%= form.submit class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/heros/edit.html.erb
<h1>Editing Hero</h1>

<%= render 'form', hero: @hero %>

<br />

<%= link_to 'Show', @hero, class: 'btn btn-primary btn-sm'  %> 
<%= link_to 'Back', heros_path, class: 'btn btn-primary btn-sm'  %> 
<%= link_to 'New avatar', new_hero_file_upload_path(@hero), class: 'btn btn-success btn-sm'  %>

<% if @hero.files.sample %>
  <h5>Avatar files</h5> 

  <div class="row">
    <% @hero.files.each do |file| %>
      <div class="col-sm-6 col-md-6 col-lg-4">
        <%= image_tag file, width: 200, class: 'float-left', style: 'margin-right: 12px;', alt: '' %>
        <%= link_to "Remove", hero_file_upload_path(@hero, file), class: '', method: :delete, data: { confirm: "Tem certeza?" } %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/heros/index.html.erb
<h1>Heros</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th>Movies</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.name %></td>
        <td><%= hero.bio %></td>
        <td><%= hero.birthday %></td>
        <td><%= hero.movies %></td>
        <td>
          <%= link_to 'Show', hero, class: 'btn btn-info btn-sm'  %>
          <%= link_to 'Edit', edit_hero_path(hero), class: 'btn btn-success btn-sm' %>
          <%= link_to 'Destroy', hero, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hero', new_hero_path, class: 'btn btn-primary btn-sm' %>

app/views/heros/new.html.erb
<h1>New Hero</h1>

<%= render 'form', hero: @hero %>

<br />

<%= link_to 'Back', heros_path, class: 'btn btn-primary btn-sm' %>

app/views/heros/show.html.erb
<%= image_tag(@hero.files.first, width: 200, class: 'float-left', style: 'margin-right: 12px;', alt: '') if @hero.files.first %>

<p>
  <strong>Name:</strong>
  <%= @hero.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @hero.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @hero.birthday %>
</p>

<p>
  <strong>Movies:</strong>
  <%= @hero.movies %>
</p>

<%= link_to 'Edit', edit_hero_path(@hero) %> |
<%= link_to 'Back', heros_path %>

app/views/home/_hero.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= hero.name %></h5>
    <% if hero.files.first %>
      <%= link_to image_tag(hero.files.first, width: 200, class: 'float-right', style: 'margin-right: 12px;', alt: ''), hero %>
    <% else %>
      <%= link_to image_tag('avatar_default.jpg', width: 200, class: 'float-right', style: 'margin-right: 12px;', alt: ''), hero %>
    <% end %>
  </div>
</div>

app/views/home/_list_hero.html.erb
<div class="row">
  <% @heroes.each do |hero| %>
    <div class="col-sm-6 col-md-6 col-lg-4">
      <%= render 'hero', hero: hero %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Heroes</h1>

<%= render 'list_hero', heroes: @heroes %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light bg-light">
      <%= link_to "Home", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item ">
            <%= link_to "Hero",heros_path, :class => "nav-link" %>
          </li>  
        </ul>
        <%= form_tag(root_path, method: 'get', class: 'form-inline my-2 my-lg-0') do %>
          <%= search_field_tag 'search', nil, class: 'form-control form-control-sm mr-sm-2', placeholder: 'Search'  %>
          <%= submit_tag "Submit", class: 'btn btn-sm btn-outline-success my-2 my-sm-0', :name => nil %>
        <% end %>               
      </div>
    </nav>

    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>      
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>